export const ProjectConstants = {
    ADD_PROJECT: "ADD_PROJECT",
    REMOVE_PROJECT: "REMOVE_PROJECT",
    UPDATE_PROJECT: "UPDATE_PROJECT",
}

export const TaskConstants = {
    ADD_TASK: "ADD_TASK",
    REMOVE_TASK: "REMOVE_TASK",
    SET_TASK_AS_COMPLETED: "SET_TASK_AS_COMPLETED"
}